version: '3'

services:
  elrond-import-db-mainnet-0:
    ulimits:
      nproc: 65535
    image: elrond-import-db-mainnet:latest
    container_name: elrond-import-db-mainnet-0
    ports:
      - "4080:8080"
      - "47370:37373"
    volumes:
      - ${HOME}/deep-history-workdir/import-db/mainnet/node-0:/data
    command: --destination-shard-as-observer=0
    networks:
      elrond-import-db-mainnet:
        ipv4_address: 10.0.0.10
    profiles:
      - donotstart

  elrond-import-db-mainnet-1:
    ulimits:
      nproc: 65535
    image: elrond-import-db-mainnet:latest
    container_name: elrond-import-db-mainnet-1
    ports:
      - "4081:8080"
      - "47371:37373"
    volumes:
      - ${HOME}/deep-history-workdir/import-db/mainnet/node-1:/data
    command: --destination-shard-as-observer=1
    networks:
      elrond-import-db-mainnet:
        ipv4_address: 10.0.0.11
    profiles:
      - donotstart

  elrond-import-db-mainnet-2:
    ulimits:
      nproc: 65535
    image: elrond-import-db-mainnet:latest
    container_name: elrond-import-db-mainnet-2
    ports:
      - "4082:8080"
      - "47372:37373"
    volumes:
      - ${HOME}/deep-history-workdir/import-db/mainnet/node-2:/data
    command: --destination-shard-as-observer=2
    networks:
      elrond-import-db-mainnet:
        ipv4_address: 10.0.0.12

  elrond-import-db-mainnet-metachain:
    ulimits:
      nproc: 65535
    image: elrond-import-db-mainnet:latest
    container_name: elrond-import-db-mainnet-metachain
    ports:
      - "4083:8080"
      - "47373:37373"
    volumes:
      - ${HOME}/deep-history-workdir/import-db/mainnet/node-metachain:/data
    command: --destination-shard-as-observer=metachain
    networks:
      elrond-import-db-mainnet:
        ipv4_address: 10.0.0.13
    profiles:
      - donotstart

networks:
  elrond-import-db-mainnet:
    ipam:
      config:
        - subnet: 10.0.0.0/24
