version: '3'

services:
  deep-history-observer-mainnet-0:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-mainnet:latest
    container_name: deep-history-observer-mainnet-0
    ports:
      - "1080:8080"
      - "17370:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/mainnet/node-0:/data
    command: --destination-shard-as-observer=0 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.10
    restart: always
    profiles:
      - mainnet-0

  deep-history-observer-mainnet-1:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-mainnet:latest
    container_name: deep-history-observer-mainnet-1
    ports:
      - "1081:8080"
      - "17371:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/mainnet/node-1:/data
    command: --destination-shard-as-observer=1 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.11
    restart: always
    profiles:
      - mainnet-1

  deep-history-observer-mainnet-2:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-mainnet:latest
    container_name: deep-history-observer-mainnet-2
    ports:
      - "1082:8080"
      - "17372:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/mainnet/node-2:/data
    command: --destination-shard-as-observer=2 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.12
    restart: always
    profiles:
      - mainnet-2

  deep-history-observer-mainnet-metachain:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-mainnet:latest
    container_name: deep-history-observer-mainnet-metachain
    ports:
      - "1083:8080"
      - "17373:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/mainnet/node-metachain:/data
    command: --destination-shard-as-observer=metachain --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.13
    restart: always
    profiles:
      - mainnet-metachain

  deep-history-proxy-mainnet:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-proxy-mainnet:latest
    container_name: deep-history-observer-mainnet-0
    ports:
      - "8080:8080"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/mainnet/proxy:/data
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.14
    restart: always
    profiles:
      - mainnet-proxy

  deep-history-observer-devnet-0:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-devnet:latest
    container_name: deep-history-observer-devnet-0
    ports:
      - "2080:8080"
      - "27370:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/devnet/node-0:/data
    command: --destination-shard-as-observer=0 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.20
    restart: always
    profiles:
      - devnet-0

  deep-history-observer-devnet-1:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-devnet:latest
    container_name: deep-history-observer-devnet-1
    ports:
      - "2081:8080"
      - "27371:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/devnet/node-1:/data
    command: --destination-shard-as-observer=1 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.21
    restart: always
    profiles:
      - devnet-1

  deep-history-observer-devnet-2:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-devnet:latest
    container_name: deep-history-observer-devnet-2
    ports:
      - "2082:8080"
      - "27372:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/devnet/node-2:/data
    command: --destination-shard-as-observer=2 --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.22
    restart: always
    profiles:
      - devnet-2

  deep-history-observer-devnet-metachain:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-observer-devnet:latest
    container_name: deep-history-observer-devnet-metachain
    ports:
      - "2083:8080"
      - "27373:37373"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/devnet/node-metachain:/data
    command: --destination-shard-as-observer=metachain --serialize-snapshots --disable-consensus-watchdog
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.23
    restart: always
    profiles:
      - devnet-metachain

  deep-history-proxy-devnet:
    ulimits:
      nproc: 65535
    image: elrondnetwork/deep-history-proxy-devnet:latest
    container_name: deep-history-observer-devnet-0
    ports:
      - "9090:8080"
    volumes:
      - ${DEEP_HISTORY_WORKSPACE}/devnet/proxy:/data
    networks:
      deep-history-squad:
        ipv4_address: 12.0.0.24
    restart: always
    profiles:
      - devnet-proxy

networks:
  deep-history-squad:
    ipam:
      config:
        - subnet: 12.0.0.0/24
