name: Build & publish

on:
  workflow_dispatch:
    inputs:
      latest:
        description: "Push with tag 'latest'"
        required: false
        type: boolean

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: ./Dockerfile
          tags: elrondnetwork/deep-history:${{ github.ref_name }}

      - name: Push to "latest"
        if: ${{ inputs.latest }} == true
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: ./Dockerfile
          tags: elrondnetwork/deep-history:latest
